### ISSUE TITLE
Support Regex as character set

### ISSUE THREAD

**Issue by pepsighan** [nikolay-govorov/nanoid#2]
Is it possible to use characters from a Regex?
Typing each and every custom character takes a while.

**Comment by mrdimidium** [comment]
Hello. You want alphabet is a regular expression? Why is it necessary? How to use it?

**Comment by TheIronBorn** [comment]
You can create the alphabet with something like this if that's what you're looking for.
```rust
(b'a'..=b'z').chain(b'0'..=b'9').map(|c| c as char).collect()
```
