### ISSUE TITLE
Unique String ?

### ISSUE THREAD

**Issue by NelDav** [nikolay-govorov/nanoid#23]
In your description, you talk about a unique string ID.
But I cannot find any code which guarantees that the string is unique.

Am I misunderstanding the description or am I missing the relevant code?
If there is no guarantee that the string is unique, maybe the word _unique_ in the description should be removed.

**Comment by mrdimidium** [comment]
Hey.

The point is that with the alphabet and default length (21 char), it will take ~ 149 billion years to have a 1% probability of at least one collision. This can be considered a unique string.

More about: [Birthday problem](https://en.wikipedia.org/wiki/Birthday_problem), [Collisions](https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions)

**Comment by NelDav** [comment]
Thank you very much. I only want to be sure if I missed something in the code. I need to be sure that the strings are unique. Because that I wrapped nanoid to checks if any string already appeared before.

/close
