### ISSUE TITLE
Dictionary list

### ISSUE THREAD

**Issue by mrdimidium** [nikolay-govorov/nanoid#7]
For JS version there is [`nanoid-dictionary`](https://github.com/CyberAP/nanoid-dictionary) - a set of additional dictionaries. Perhaps we should add them to the Rust version?

**Comment by mrdimidium** [comment]
@ai

**Comment by ai** [comment]
To be honest, dictionary is not really popular https://npm-stat.com/charts.html?package=nanoid-dictionary

**Comment by mrdimidium** [comment]
Maybe because the people writing the dictionaries themselves?

**Comment by ai** [comment]
Yeap. Seems like for them it is a better option.

**Comment by imp** [comment]
Just in case anyone is looking here - [nanoid-dictionary](https://docs.rs/nanoid-dictionary)
